# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_null <- function(type, term_sets_data, use_mean, group_size, samples) {
    .Call('_ontologySimilarity_sample_null', PACKAGE = 'ontologySimilarity', type, term_sets_data, use_mean, group_size, samples)
}

sim_p <- function(type, term_sets_data, use_mean, group, min_its, max_its, signif, dismiss) {
    .Call('_ontologySimilarity_sim_p', PACKAGE = 'ontologySimilarity', type, term_sets_data, use_mean, group, min_its, max_its, signif, dismiss)
}

group_sim <- function(type, term_sets_data, use_mean, group) {
    .Call('_ontologySimilarity_group_sim', PACKAGE = 'ontologySimilarity', type, term_sets_data, use_mean, group)
}

sim_grid <- function(term_ids1, case_ids1, num_cases1, term_ids2, case_ids2, num_cases2, ttsm) {
    .Call('_ontologySimilarity_sim_grid', PACKAGE = 'ontologySimilarity', term_ids1, case_ids1, num_cases1, term_ids2, case_ids2, num_cases2, ttsm)
}

calc_term_sim_mat <- function(anc_start, anc_stop, ancestors, info, terms1, terms2) {
    .Call('_ontologySimilarity_calc_term_sim_mat', PACKAGE = 'ontologySimilarity', anc_start, anc_stop, ancestors, info, terms1, terms2)
}

sim_grid_ic <- function(lin, anc_start, anc_stop, ancestors, info, term_ids1, case_ids1, num_cases1, term_ids2, case_ids2, num_cases2) {
    .Call('_ontologySimilarity_sim_grid_ic', PACKAGE = 'ontologySimilarity', lin, anc_start, anc_stop, ancestors, info, term_ids1, case_ids1, num_cases1, term_ids2, case_ids2, num_cases2)
}

